### ISSUE TITLE
报错You need to install the latest version of Visual Studio gyp ERR! find VS including the "Desktop development with C++" workload. gyp ERR! find VS For more information consult the documentation at: gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows

### ISSUE THREAD

**Issue by shilibi** [ChengHo/CinemaBookingSystem#5]
我按照说明装了VS2022，然后配置好了，但是还是报这个错误。然后尝试安装在命令行安装windows-build-tools，仍然报错。请问如何解决，或者有没有sass-loader的替代品？报错详细信息如下：
```
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v79-win32-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.5.2 and node@13.10.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v79-win32-x64.tar.gz 
gyp ERR! find VS 
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2022
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\node\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\node\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\node\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\node\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\node\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\node\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\node\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\node\\node.exe" "C:\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=H:\\movie\\front\\panda-user\\node_modules\\nodejieba\\build\\Release\\nodejieba.node" "--module_name=nodejieba" "--module_path=H:\\movie\\front\\panda-user\\node_modules\\nodejieba\\build\\Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79" "--python=C:/Python27/python.exe" "--msvs_version=2022"
gyp ERR! cwd H:\movie\front\panda-user\node_modules\nodejieba
gyp ERR! node -v v13.10.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\node\node.exe C:\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=H:\movie\front\panda-user\node_modules\nodejieba\build\Release\nodejieba.node --module_name=nodejieba --module_path=H:\movie\front\panda-user\node_modules\nodejieba\build\Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79 --python=C:/Python27/python.exe --msvs_version=2022' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (H:\movie\front\panda-user\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.22000
node-pre-gyp ERR! command "C:\\node\\node.exe" "H:\\movie\\front\\panda-user\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd H:\movie\front\panda-user\node_modules\nodejieba
node-pre-gyp ERR! node -v v13.10.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok
Failed to execute 'C:\node\node.exe C:\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=H:\movie\front\panda-user\node_modules\nodejieba\build\Release\nodejieba.node --module_name=nodejieba --module_path=H:\movie\front\panda-user\node_modules\nodejieba\build\Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79 --python=C:/Python27/python.exe --msvs_version=2022' (1)
```

**Comment by shilibi** [comment]
解决了，通过更换node版本为14即可。
